name: Example Go Docker CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-push:
    uses: davidsugianto/shared-workflows/.github/workflows/go-docker-ci.yaml@master
    with:
      go-version: "1.25"
      image-name: "docker.io/my-dockerhub-username/my-go-app"
      run-tests: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  update-image-tag:
    needs: build-and-push
    uses: davidsugianto/shared-workflows/.github/workflows/kustomize-image-tag.yaml@master
    with:
      image: "docker.io/my-dockerhub-username/my-go-app"
      tag: ${{ needs.build-and-push.outputs.image-tag }}
      kustomize-path: "my-go-app/deployment/kubernetes/overlays/production/kustomization.yaml"
    secrets:
      GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
